name: Deploy React App to Hostinger via FTP

on:
  push:
    branches:
      - main  # Substitua se sua branch principal tiver outro nome

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Versão compatível com seu projeto

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: build  # Certifique-se de que a pasta gerada pelo build seja 'build'
        protocol: ftp       # Use 'ftps' se estiver usando FTP seguro
