name: Deploy React App to Hostinger via FTP

on:
  push:
    branches:
      - main  # Substitua se sua branch principal tiver outro nome

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Debug - List Files
        run: |
          ls -la
          ls -la dist/ || echo "Diretório dist/ não encontrado"

      - name: Check Network
        run: |
          echo "Tentando verificar conectividade com o servidor FTP..."
          nslookup ${{ secrets.FTP_SERVER }} || echo "Não foi possível resolver o nome do servidor"
          ping -c 3 ${{ secrets.FTP_SERVER }} || echo "Ping não disponível"

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./dist/
          server-dir: public_html/
          dangerous-clean-slate: true
