
name: Deploy React App to Hostinger via FTP

on:
  push:
    branches:
      - main  # Substitua se sua branch principal tiver outro nome

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Usando '18.x' para cobrir todas as subversões da versão 18

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21  # A porta padrão FTP é 21, vamos definir explicitamente
        local-dir: ./dist/       # Certifique-se que esse caminho está correto
        server-dir: ./           # Define o diretório raiz no servidor FTP
        dangerous-clean-slate: true  # Limpa o diretório remoto antes de subir os arquivos (tenha cuidado!)
